# Azure DevOps Configuration
variables:
  keyVaultName: 'qualysops-kv'
  resourceGroupName: 'qualysops-rg'
  location: 'eastus'
  
# Environment-specific configurations
environments:
  development:
    staticWebAppName: 'qualysops-dev'
    functionAppName: 'qualysops-api-dev'
    
  production:
    staticWebAppName: 'qualysops-prod'
    functionAppName: 'qualysops-api-prod'

# Monitoring configuration
monitoring:
  applicationInsights:
    enabled: true
    samplingPercentage: 100
    
# Notification settings
notifications:
  email:
    enabled: true
    recipients:
      - devops@yourcompany.com
  slack:
    enabled: true
    webhook: '$(SLACK_WEBHOOK_URL)'